apiVersion: "cilium.io/v2alpha1"
kind: CiliumL2AnnouncementPolicy
metadata:
  name: policy1
spec:
  serviceSelector:
    matchLabels: {}
  nodeSelector:
    matchExpressions:
      - key: node-role.kubernetes.io/control-plane
        operator: DoesNotExist
  interfaces:
  - ^ens[0-9]+    # how to find the correct  interfaces?
  externalIPs: true   # ???
  loadBalancerIPs: true   #  laat toe dat gateway api dit kan gebruiken????
