# example
apiVersion: "cilium.io/v2alpha1"
kind: CiliumL2AnnouncementPolicy
metadata:
  name: policy1 # naam van de L2announcement
spec:
  serviceSelector:
    matchLabels: {}
  nodeSelector: # selecteer op welke node
    matchExpressions:
      - key: node-role.kubernetes.io/control-plane # Selecteer de control-plane nodes
        operator: DoesNotExist   # niet op de control plane nodes
  interfaces:
  - ^ens[0-9]+    # how to find the correct  interfaces?
  externalIPs: true   # laat to dat je zelf een extern IP toewijzen
  loadBalancerIPs: true   #  laat toe dat gateway api dit kan gebruiken????


---

apiVersion: "cilium.io/v2alpha1"
kind: CiliumL2AnnouncementPolicy
metadata:
  name: policy1
spec:
  serviceSelector:
    matchLabels: {}
  nodeSelector:
    matchExpressions:
      - key: node-role.kubernetes.io/control-plane
        operator: DoesNotExist
  interfaces:
  - ens33
  externalIPs: true
  loadBalancerIPs: true
