nodes:
  # Wazuh indexer nodes
  indexer:
    - name: wazuh-1
      ip: "172.24.1.81"
    - name: wazuh-2
      ip: "172.24.1.82"
    - name: wazuh-3
      ip: "172.24.1.83"

  # Wazuh server nodes
  server:
    - name: wazuh-1
      ip: "172.24.1.81"
      node_type: master
    - name: wazuh-2
      ip: "172.24.1.82"
      node_type: worker

  # Wazuh dashboard nodes
  dashboard:
    - name: wazuh-1
      ip: "172.24.1.81"
    - name: wazuh-2
      ip: "172.24.1.82"
