apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaultwarden-postgres
  namespace: ns-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vaultwarden-postgres
  template:
    metadata:
      labels:
        app: vaultwarden-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:13
        env:
        - name: POSTGRES_DB
          value: vaultwarden
        - name: POSTGRES_USER
          value: vaultwarden
        - name: POSTGRES_PASSWORD
          value: strongpassword
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-data
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: vaultwarden-postgres
  namespace: ns-management
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: vaultwarden-postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaultwarden
  namespace: ns-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vaultwarden
  template:
    metadata:
      labels:
        app: vaultwarden
    spec:
      containers:
      - name: vaultwarden
        image: vaultwarden/server:latest
        env:
        - name: DATABASE_URL
          value: "postgresql://vaultwarden:strongpassword@vaultwarden-postgres:5432/vaultwarden"
        - name: ADMIN_TOKEN
          valueFrom:
            secretKeyRef:
              name: vaultwarden-secret
              key: ADMIN_TOKEN
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /data
          name: vaultwarden-data
      volumes:
      - name: vaultwarden-data
        persistentVolumeClaim:
          claimName: vaultwarden-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: vaultwarden
  namespace: ns-management
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: vaultwarden
