---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden-pvc
  namespace: ns-management
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: vaultwarden-pv
  storageClassName: nfs

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: vaultwarden-pv
  namespace: ns-management
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /mnt/Main/Apps/Vaultwarden/vaultwarden
    server: 172.24.1.99
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: ns-management
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: postgres-pv
  storageClassName: nfs
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: ns-management
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /mnt/Main/Apps/Vaultwarden/postgres
    server: 172.24.1.99
---
