apiVersion: v1
kind: Namespace
metadata:
  name: ns-management
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: vaultwarden-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /mnt/Main/Apps/Vaultwarden
    server: 172.24.1.99
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden-pvc
  namespace: ns-management
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: vaultwarden-pv
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaultwarden-postgres
  namespace: ns-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vaultwarden-postgres
  template:
    metadata:
      labels:
        app: vaultwarden-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:13
        env:
        - name: POSTGRES_DB
          value: vaultwarden
        - name: POSTGRES_USER
          value: vaultwarden
        - name: POSTGRES_PASSWORD
          value: strongpassword
        ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: vaultwarden-postgres
  namespace: ns-management
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: vaultwarden-postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaultwarden
  namespace: ns-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vaultwarden
  template:
    metadata:
      labels:
        app: vaultwarden
    spec:
      containers:
      - name: vaultwarden
        image: vaultwarden/server:latest
        env:
        - name: DATABASE_URL
          value: "postgresql://vaultwarden:strongpassword@vaultwarden-postgres:5432/vaultwarden"
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /data
          name: vaultwarden-data
      volumes:
      - name: vaultwarden-data
        persistentVolumeClaim:
          claimName: vaultwarden-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: vaultwarden
  namespace: ns-management
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: vaultwarden
