apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-hosting
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /mnt/Main/Apps/Website/wordpress/
    server: 172.24.1.99
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-mariadb-pv-hosting
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /mnt/Main/Apps/Website/mysql
    server: 172.24.1.99
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-hosting
  namespace: ns-management
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-mariadb-hosting
  namespace: ns-management
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
