apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb
          image: yobasystems/alpine-mariadb
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: HDt24a7W2kow6XQsxequyR
            - name: MYSQL_DATABASE
              value: wordpress-db
            - name: MYSQL_USER
              value: db-user
            - name: MYSQL_PASSWORD
              value: yGzZqJKD4YzZMRtskmopQa
          volumeMounts:
            - name: mypvc #mypvc
              mountPath: /var/lib/mysql
      volumes:
        - name: mypvc   #mypvc
          persistentVolumeClaim:
            claimName: nfs-pvc