apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: bloedlink/wordpress-nodatabase
          ports:
            - containerPort: 80
          env:
            - name: WORDPRESS_DB_HOST
              value: db
            - name: WORDPRESS_DB_USER
              value: db-user
            - name: WORDPRESS_DB_PASSWORD
              value: yGzZqJKD4YzZMRtskmopQa
            - name: WORDPRESS_DB_NAME
              value: wordpress-db
          volumeMounts:
            - name: mypvc #mypvc
              mountPath: /usr/html/
      volumes:
        - name: mypvc   #mypvc
          persistentVolumeClaim:
            claimName: nfs-pvc
---

apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
spec:
  selector:
    app: wordpress
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer