apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflare-config
  namespace: lemp-stack
data:
  config.yaml: |
    tunnel: 3bb358bc-d87a-438c-9022-3b44717142d1
    credentials-file: /etc/cloudflared/3bb358bc-d87a-438c-9022-3b44717142d1.json
    ingress:
      - hostname: test.bloedlinks.app
        service: http://nginx.lemp-stack.svc.cluster.local:80
      - service: http_status:404

    originRequest:
      noTLSVerify: true
    logLevel: info
    warp-routing:
      enabled: true
    dns:
      - address: 10.96.0.10
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: lemp-stack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      dnsPolicy: ClusterFirst
      containers:
      - name: cloudflared
        image: cloudflare/cloudflared:latest
        args: ["tunnel", "--config", "/etc/cloudflared/config.yaml", "run"]
        env:
        - name: TUNNEL_TOKEN
          value: "eyJhIjoiMWIwZGEyNzdiY2YzN2QxYjUxMjViMTFhOTBkYTNkMzEiLCJzIjoicU80bDJUVGlMWEFCdFRWMHI1VVc5ciszb2J4RGY0VnA2RG5nSlAxUjZucz0iLCJ0IjoiM2JiMzU4YmMtZDg3YS00MzhjLTkwMjItM2I0NDcxNzE0MmQxIn0="
        volumeMounts:
        - name: config
          mountPath: /etc/cloudflared
      volumes:
      - name: config
        configMap:
          name: cloudflare-config
