apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.identifier }}-nfs-pvc
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.identifier }}-nfs-pvc-{{ .Values.database.type }}
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
