apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.identifier }}-db-credentials
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  WORDPRESS_DB_USER: {{ .Values.dbCredentials.user }}
  WORDPRESS_DB_PASSWORD: {{ .Values.dbCredentials.password }}
  WORDPRESS_DB_NAME: {{ .Values.dbCredentials.dbName }}
  MYSQL_ROOT_PASSWORD: {{ .Values.dbCredentials.rootPassword }}
  MYSQL_DATABASE: {{ .Values.dbCredentials.mysqlDatabase }}
  MYSQL_USER: {{ .Values.dbCredentials.mysqlUser }}
  MYSQL_PASSWORD: {{ .Values.dbCredentials.mysqlPassword }}
