apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: ns-management
spec:
  selector:
    app: nginx
  type: NodePort
  ports:
    - protocol: TCP
      nodePort: 30080
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: php-fpm
  namespace: ns-management
spec:
  selector:
    app: php-fpm
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: ns-management
spec:
  selector:
    app: mariadb
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
