apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: ns-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      initContainers:
      - name: init-nginx
        image: busybox
        command: ['sh', '-c', 'mkdir -p /etc/nginx/snippets && cp /config/fastcgi-php.conf /etc/nginx/snippets/fastcgi-php.conf && ls -l /etc/nginx/snippets']
        volumeMounts:
        - name: nginx-snippets
          mountPath: /config
      containers:
      - name: nginx
        image: nginx:latest
        env:
          - name: WORDPRESS_DB_HOST
            value: mariadb
          - name: WORDPRESS_DB_USER
            valueFrom:
              secretKeyRef:
                name: db-credentials-hosting
                key: WORDPRESS_DB_USER
          - name: WORDPRESS_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-credentials-hosting
                key: WORDPRESS_DB_PASSWORD
          - name: WORDPRESS_DB_NAME
            valueFrom:
              secretKeyRef:
                name: db-credentials-hosting
                key: WORDPRESS_DB_NAME
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "512Mi"
            cpu: "800m"
          limits:
            memory: "1024Mi"
            cpu: "1000m"
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
        - name: nginx-snippets
          mountPath: /etc/nginx/snippets
        - name: web-content
          mountPath: /var/www/html
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
      - name: nginx-snippets
        configMap:
          name: nginx-snippets
      - name: web-content
        persistentVolumeClaim:
          claimName: nfs-pvc-hosting
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-fpm
  namespace: ns-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-fpm
  template:
    metadata:
      labels:
        app: php-fpm
    spec:
      containers:
      - name: php-fpm
        image: wordpress:php8.1-fpm
        ports:
        - containerPort: 9000
        volumeMounts:
        - name: web-content
          mountPath: /var/www/html
      volumes:
      - name: web-content
        persistentVolumeClaim:
          claimName: nfs-pvc-hosting
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  namespace: ns-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: mariadb:latest
        ports:
        - containerPort: 3306
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-credentials-hosting
                key: MYSQL_ROOT_PASSWORD
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: db-credentials-hosting
                key: MYSQL_DATABASE
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: db-credentials-hosting
                key: MYSQL_USER
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-credentials-hosting
                key: MYSQL_PASSWORD
        volumeMounts:
        - name: mariadb-data
          mountPath: /var/lib/mysql
      volumes:
      - name: mariadb-data
        persistentVolumeClaim:
          claimName: nfs-pvc-mariadb-hosting
